title: Notes
tagline: Evidentia
description: "Notes sur l'organisation, la modernisation et les ressources techniques des PME et ETI."
author: Nicolas Berthier
email: contact@evidentia.fr
url: "https://notes.evidentia.fr"
baseurl: ""

markdown: kramdown

plugins:
  - jekyll-feed

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
