title: Evidentia Notes
tagline: Evidentia
description: "Notes"
author: Guillaume Ansanay-Alex
email: contact@evidentia.fr
url: "https://notes.evidentia.fr"
baseurl: ""

markdown: kramdown

plugins:
  - jekyll-feed

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
